class GetUnitInfo:
  def SaveUnitInfoToCsv(self, scenarioFile: str, outputPath: str) -> None: ...
  def GetUnitListString(self, scenarioFile: str) -> List`1: ...
  def PrintFieldsTest(self, scenarioFile: str) -> None: ...
  def GetType(self) -> type: ...
  def ToString(self) -> str: ...
  def Equals(self, obj: object) -> bool: ...
  def GetHashCode(self) -> int: ...
class MapRevealer:
  def RevealedMap(self, savePath: str) -> bytes: ...
  def GetType(self) -> type: ...
  def ToString(self) -> str: ...
  def Equals(self, obj: object) -> bool: ...
  def GetHashCode(self) -> int: ...
class PlayerToggler:
  def __init__(self): ...
  def GetHumanPlayers(self, saveBytes: bytes) -> list[bool]: ...
  def GetRemainingPlayers(self, saveBytes: bytes) -> list[bool]: ...
  def SetHumanPlayer(self, saveBytes: bytes, playerSlot: int, isHuman: bool) -> None: ...
  def GetType(self) -> type: ...
  def ToString(self) -> str: ...
  def Equals(self, obj: object) -> bool: ...
  def GetHashCode(self) -> int: ...
class StructBuilders:
  def GetGameData(self, savPath: str) -> Nullable`1: ...
  def GetGameData(self, saveBytes: bytes) -> Nullable`1: ...
  def GetBiqGameData(self, biqPath: str) -> Nullable`1: ...
  def GetBiqGameData(self, biqBytes: bytes) -> Nullable`1: ...
  def GetTileData(self, savPath: str) -> TILE_VP[]: ...
  def GetTileData(self, saveBytes: bytes) -> TILE_VP[]: ...
  def GetType(self) -> type: ...
  def ToString(self) -> str: ...
  def Equals(self, obj: object) -> bool: ...
  def GetHashCode(self) -> int: ...
class PitBossOrganizer:
  def __init__(self, firstSavFile: bytes, humanPlayers: list[str]): ...
  def get_Fingerprint(self) -> str: ...
  def get_HumanPlayers(self) -> list[str]: ...
  def get_DefaultAI(self) -> list[bool]: ...
  def get_LastPlayerHuman(self) -> bool: ...
  def get_CurrentTurn(self) -> int: ...
  def get_CurrentPlayer(self) -> int: ...
  def get_DecompressedSave(self) -> bytes: ...
  def get_TurnTaken(self) -> list[bool]: ...
  def get_AdminPassword(self) -> str: ...
  def GetConfiguredTurn(self, player: str) -> bytes: ...
  def ReceiveNewTurn(self, newSave: bytes) -> None: ...
  def ToggleDefaultAI(self, playerSlot: int) -> bool: ...
  def ToggleLastPlayerHuman(self) -> bool: ...
  def GetDummyTurn(self) -> bytes: ...
  def ReceiveDummyTurn(self, dummySave: bytes) -> None: ...
  def ForceUnlock(self) -> None: ...
  def ChangePlayerOrder(self, newOrder: list[str]) -> None: ...
  def Dispose(self) -> None: ...
  def GetType(self) -> type: ...
  def ToString(self) -> str: ...
  def Equals(self, obj: object) -> bool: ...
  def GetHashCode(self) -> int: ...
class TurnOrchestrator:
  def GetGameFingerprint(self, saveBytes: bytes) -> str: ...
  def GetNextPlayerID(self, saveBytes: bytes) -> Nullable`1: ...
  def WriteNextPlayerID(self, saveBytes: bytes, id: int) -> None: ...
  def WriteTurnNumber(self, saveBytes: bytes, turn: int) -> None: ...
  def GetType(self) -> type: ...
  def ToString(self) -> str: ...
  def Equals(self, obj: object) -> bool: ...
  def GetHashCode(self) -> int: ...
class VictoryPointRandomizer:
  def GetType(self) -> type: ...
  def ToString(self) -> str: ...
  def Equals(self, obj: object) -> bool: ...
  def GetHashCode(self) -> int: ...
class <PrivateImplementationDetails>:
  def GetType(self) -> type: ...
  def ToString(self) -> str: ...
  def Equals(self, obj: object) -> bool: ...
  def GetHashCode(self) -> int: ...
class <>c:
  def __init__(self): ...
  def GetType(self) -> type: ...
  def ToString(self) -> str: ...
  def Equals(self, obj: object) -> bool: ...
  def GetHashCode(self) -> int: ...
class <>c__DisplayClass3_0:
  def __init__(self): ...
  def GetType(self) -> type: ...
  def ToString(self) -> str: ...
  def Equals(self, obj: object) -> bool: ...
  def GetHashCode(self) -> int: ...
class <>c__DisplayClass7_0:
  def __init__(self): ...
  def GetType(self) -> type: ...
  def ToString(self) -> str: ...
  def Equals(self, obj: object) -> bool: ...
  def GetHashCode(self) -> int: ...
class <GetIgnoredTerrainIndexes>d__2:
  def __init__(self, <>1__state: int): ...
  def GetType(self) -> type: ...
  def ToString(self) -> str: ...
  def Equals(self, obj: object) -> bool: ...
  def GetHashCode(self) -> int: ...
class TILE_VP:
  def Equals(self, obj: object) -> bool: ...
  def GetHashCode(self) -> int: ...
  def ToString(self) -> str: ...
  def GetType(self) -> type: ...
class <Flags2>e__FixedBuffer:
  def Equals(self, obj: object) -> bool: ...
  def GetHashCode(self) -> int: ...
  def ToString(self) -> str: ...
  def GetType(self) -> type: ...
